#include "PromptModelDefinitions.h"

const std::vector<PromptModelDefinitions::ModelInfo> &PromptModelDefinitions::getAllModels()
{
	static std::vector<ModelInfo> models = {
	    {"stable-audio-open-1.0",
	     "Natural language descriptive prompts. Format: [Style/Genre], [Key Elements], [Mood], [Details]",
	     {
	         {"Genres",
	          {"techno", "house", "trap", "drum and bass", "ambient", "hip-hop", "jungle", "dub", "industrial",
	           "hardcore", "breakbeat", "lo-fi", "synthwave", "psychedelic"}},
	         {"Elements",
	          {"kick drum loop", "bassline", "hi-hat loop", "snare pattern", "percussion loop", "synth melody", "lead",
	           "pad", "arpeggio", "vocal chops", "noise stabs"}},
	         {"Moods",
	          {"dark", "warm", "aggressive", "chill", "melancholic", "euphoric", "dreamy", "haunting", "uplifting",
	           "moody", "raw", "ethereal"}},
	         {"Qualities",
	          {"solo", "isolated", "dry", "rhythmic", "monophonic", "driving", "rolling", "punchy", "crisp", "deep",
	           "warm", "distorted", "metallic", "squelchy"}},
	         {"Negatives", {"no background elements", "no pads", "no melody", "no accompaniment", "no rhythm"}},
	     },
	     {
	         "deep dub kick loop, solo kick pattern, sub-heavy 4/4, dry, no background",
	         "psychedelic ambient flute melody, solo flute, ethereal phrasing, dry, no rhythm",
	         "rolling jungle break loop, solo amen percussion, chopped, dry, isolated",
	         "warm analog lead melody, solo monophonic synth, soft saw wave, dry",
	         "industrial noise stabs, solo distorted hits, rhythmic, dry, no melodic content",
	         "minimal techno hi-hat loop, solo metallic hi-hats, off-beat, dry, isolated",
	     }},

	    {"stable-audio-3-medium",
	     "Universal Multi-mode engine. Stems must use 'TrackType: Instrument'. FX must use 'TrackType: SFX'. NO "
	     "BPM/Key.",
	     {
	         {"Track Types", {"TrackType: Instrument", "TrackType: SFX"}},
	         {"Formats & Global Genres",
	          {"Format: Solo", "Format: Duo", "Blues", "Rock", "Metal", "Jazz", "Electronic", "Hip-Hop", "Urban", "Pop",
	           "Classical", "Avant-Garde", "Experimental", "Folk", "World Music", "Cinematic", "Ambient"}},
	         {"Electronic & Dance Sub-Genres", {"House",
	                                            "Deep House",
	                                            "Tech House",
	                                            "Acid House",
	                                            "Techno",
	                                            "Minimal Techno",
	                                            "Industrial Techno",
	                                            "Dub Techno",
	                                            "Drum and Bass",
	                                            "Liquid DnB",
	                                            "Neurofunk",
	                                            "Jump Up",
	                                            "Jungle",
	                                            "Breakbeat",
	                                            "Big Beat",
	                                            "Dubstep",
	                                            "Riddim",
	                                            "Garage",
	                                            "UKG",
	                                            "Grime",
	                                            "Trance",
	                                            "Psytrance",
	                                            "Hardstyle",
	                                            "Gabber",
	                                            "Synthwave",
	                                            "Chiptune",
	                                            "Glitch Hop",
	                                            "IDM",
	                                            "Vaporwave",
	                                            "Ambiance",
	                                            "Downtempo",
	                                            "Trip Hop",
	                                            "Electro Swing"}},
	         {"Rock, Metal & Punk Sub-Genres",
	          {"Classic Rock",  "Psychedelic Rock", "Prog Rock",  "Hard Rock",        "Heavy Metal", "Thrash Metal",
	           "Death Metal",   "Black Metal",      "Doom Metal", "Sludge",           "Stoner Rock", "Djent",
	           "Math Rock",     "Post-Rock",        "Grunge",     "Alternative Rock", "Indie Rock",  "Punk Rock",
	           "Hardcore Punk", "Post-Punk",        "Goth Rock",  "Shoegaze",         "Ska"}},
	         {"Urban, Hip-Hop & R&B Sub-Genres",
	          {"Boom Bap", "East Coast Hip-Hop", "West Coast G-Funk", "Dirty South", "Trap", "Cloud Trap", "Drill",
	           "R&B", "Neo-Soul", "Funk", "P-Funk", "Disco", "Reggae", "Roots Reggae", "Dancehall", "Dub", "Ska",
	           "Reggaeton"}},
	         {"Jazz, Blues & Roots Sub-Genres",
	          {"Delta Blues", "Chicago Blues", "Texas Blues", "Ragtime", "Dixieland", "Swing Jazz", "Bebop", "Hard Bop",
	           "Cool Jazz", "Modal Jazz", "Free Jazz", "Jazz Fusion", "Lofi Jazz", "Bluegrass", "Americana",
	           "Country"}},
	         {"World, Ethnic & Folk Regional",
	          {"Afrobeat",
	           "Highlife",
	           "Kuduro",
	           "Salsa",
	           "Mambo",
	           "Merengue",
	           "Bossa Nova",
	           "Samba",
	           "Choro",
	           "Forro",
	           "Flamenco",
	           "Fado",
	           "Celtic Folk",
	           "Traditional Irish",
	           "Gypsy Jazz",
	           "Klezmer",
	           "Indian Classical",
	           "Carnatic",
	           "Hindustani",
	           "Gamelan",
	           "Andean Folk",
	           "Mariachi",
	           "Cumbia",
	           "Sufi",
	           "Traditional Chinese"}},
	         {"Classical, Cinematic & Orchestral",
	          {"Baroque", "Classical Era", "Romantic Era", "Impressionism", "Expressionism", "Minimalism",
	           "Modern Classical", "Neoclassical", "Epic Cinematic", "Dystopian Sci-Fi", "Horror Ambient",
	           "Orchestral Brass", "Chamber Strings"}},
	         {"Acoustic & Ethnic Instruments",
	          {"acoustic guitar",
	           "resonator",
	           "cigar box guitar",
	           "banjo",
	           "mandolin",
	           "fiddle",
	           "ukulele",
	           "upright bass",
	           "harp",
	           "concertina",
	           "accordion",
	           "harmonica",
	           "kora",
	           "sitar",
	           "oud",
	           "shakuhachi",
	           "tin whistle",
	           "didgeridoo",
	           "hang drum",
	           "kalimba",
	           "marimba",
	           "balalaika",
	           "bouzouki",
	           "erhu",
	           "guzheng",
	           "bagpipes",
	           "pan flute",
	           "ocarina",
	           "lute",
	           "hurdy-gurdy",
	           "saz",
	           "tar",
	           "pipa",
	           "berimbau",
	           "jaw harp"}},
	         {"Electric, Keys & Synth Instruments",
	          {"electric guitar riff",
	           "seven-string guitar",
	           "eight-string guitar",
	           "overdriven bassline",
	           "slap bass",
	           "grand piano",
	           "upright piano",
	           "rhodes keys",
	           "wurlitzer",
	           "hammond organ",
	           "clavinet",
	           "mellotron",
	           "monophonic lead",
	           "polyphonic pad",
	           "modular arp",
	           "303 acid bass",
	           "reese bass",
	           "sub-bass growl",
	           "supersaw lead",
	           "wavetable pluck",
	           "chiptune pulse wave",
	           "theremin",
	           "laser harp"}},
	         {"Drums, Percussion & Grooves",
	          {"acoustic drum-kit",
	           "brushed snare",
	           "snare rimshots",
	           "closed hi-hats",
	           "open cymbal sizzle",
	           "linn drum",
	           "808 sub kick",
	           "909 drum loop",
	           "amen break beat",
	           "taiko drum",
	           "djembe",
	           "congas",
	           "bongos",
	           "timbales",
	           "darbuka",
	           "tabla",
	           "cajon",
	           "shaker loop",
	           "tambourine",
	           "cowbell",
	           "woodblock",
	           "guiro",
	           "castanets",
	           "gong"}},
	         {"Sound Design, Textures & FX",
	          {"sub-bass boom",        "sub drop",           "electronic riser", "white noise swoop",
	           "industrial door slam", "metal scrape",       "tape-stop effect", "granular glitch",
	           "modular bleeps",       "laser shot",         "vinyl crackle",    "analog tape hiss",
	           "reverse cymbal swell", "subsonic explosion", "impact transient", "mechanical click",
	           "atmospheric drone",    "sci-fi telemetry",   "cinematic braam",  "sub-bass rumble",
	           "clock ticking",        "glass shatter",      "wind howl"}},
	         {"Acoustics, Production & Pedals", {"dry",
	                                             "isolated",
	                                             "close mic",
	                                             "room acoustics",
	                                             "cavernous reverb",
	                                             "massive hall reverb",
	                                             "plate reverb",
	                                             "spring reverb",
	                                             "slapback delay",
	                                             "ping pong delay",
	                                             "tape delay",
	                                             "high-gain distortion",
	                                             "fuzz",
	                                             "tube saturation",
	                                             "bitcrushed",
	                                             "lo-fi warmth",
	                                             "stereo chorus",
	                                             "phaser sweeps",
	                                             "flanger",
	                                             "wah-wah pedal"}},
	     },
	     {
	         "TrackType: Instrument, Format: Solo, a raw delta blues slide guitar riff, resonator acoustic guitar, "
	         "dusty vintage tone, fingerpicked, dry",
	         "TrackType: Instrument, Format: Solo, an aggressive heavy metal rhythm guitar riff, seven-string guitar, "
	         "chugging palm mutes, high-gain distortion",
	         "TrackType: Instrument, Format: Solo, a hypnotic West African kora melody, intricate plucked string "
	         "patterns, bright resonant wooden tones, dry",
	         "TrackType: Instrument, Format: Solo, a soulful Japanese shakuhachi flute melody, breathy articulation, "
	         "organic pitch inflections, cinematic zen temple acoustics",
	         "TrackType: Instrument, Format: Solo, a heavy neurobass growl loop, modulated wavetable synthesis, "
	         "aggressive tearing textures, sub-bass pressure, dry",
	         "TrackType: Instrument, Format: Solo, a squelchy acid 303 synth bassline, resonant filter sweeps, "
	         "aggressive analog texture, driving monophonic sequence, dry",
	         "TrackType: Instrument, Format: Solo, dark dystopian cinematic pad, low drone foundation, sweeping "
	         "high-frequency harmonics, tension building, massive hall reverb",
	         "TrackType: Instrument, Format: Solo, a traditional banjo clawhammer pattern, rapid double-thumbing "
	         "technique, bright metallic timbre, crisp bluegrass style",
	         "TrackType: Instrument, Format: Solo, a spacey dub melodic bassline, heavy low-end focus, reggae style "
	         "plucking, tape-delayed transient reflections",
	         "TrackType: Instrument, Format: Solo, a virtuosic flamenco guitar falsetta, rapid nylon-string rasgueado, "
	         "bright percussive wooden body taps, dry studio space",
	         "TrackType: Instrument, Format: Solo, a haunting classical solo cello melody, rich melancholic romantic "
	         "era phrasing, expressive vibrato, intimate room acoustics",
	         "TrackType: Instrument, Format: Solo, an upbeat electro swing brass section hook, jazzy muted trumpet and "
	         "saxophone duet, syncopated driving rhythm, dry",
	         "TrackType: Instrument, Format: Solo, a hypnotic minimal techno synthesizer sequence, subtle analog pulse "
	         "wave modulation, short decay, sterile close-mic feel",
	         "TrackType: Instrument, Format: Solo, a heavy funk slap bassline groove, popping strings, overdriven tube "
	         "preamp saturation, rhythmic ghost notes, tight and punchy",
	         "TrackType: Instrument, Format: Solo, a dark ambient modular synth drone, low-frequency pitch drifts, "
	         "granular texture overlays, ominous eerie space",
	         "TrackType: Instrument, Format: Solo, a lofi jazz rap rhodes piano chord progression, warm vinyl crackle "
	         "overlay, soft tremolo effect, nostalgic laid-back vibe",
	         "TrackType: SFX, a massive cinematic sub-bass boom, deep sub-sonic explosion drop, long decaying low-end "
	         "tail, transient impact",
	         "TrackType: SFX, a heavy industrial metal door slamming shut, fast decay, mechanical lock mechanism "
	         "click, "
	         "recorded in a dead concrete room",
	         "TrackType: SFX, a glitchy digital transition, tape-stop effect artifact, pitch and speed dropping "
	         "simultaneously, grinding to a halt into a sub frequency",
	         "TrackType: SFX, a metallic blade scrape, high-pitched screeching texture, friction sound, long eerie "
	         "decay, processed with a dark wooden reverb",
	         "TrackType: SFX, a cinematic sci-fi braam effect, distorted low brass hit layered with an analog "
	         "synthesizer growl, massive scale, ominous trailer transient",
	         "TrackType: SFX, a rapid digital modular synth bleep sequence, granular delay scattering, arcade chiptune "
	         "laser telemetry bursts, dry space",
	     }},

	    {"foundation-1",
	     "Structured tags. Format: [Family], [Sub-Family], [Timbre], [Notation], [FX]. Comma-separated.",
	     {
	         {"Families",
	          {"Synth", "Keys", "Bass", "Bowed Strings", "Mallet", "Wind", "Guitar", "Brass", "Vocal",
	           "Plucked Strings"}},
	         {"Sub-Families",
	          {"Synth Lead",
	           "Synth Bass",
	           "FM Synth",
	           "FM Bass",
	           "Wavetable Synth",
	           "Wavetable Bass",
	           "Supersaw",
	           "Reese Bass",
	           "Sub Bass",
	           "Electric Bass",
	           "Pad",
	           "Atmosphere",
	           "Texture",
	           "Bell",
	           "Pluck",
	           "Grand Piano",
	           "Digital Piano",
	           "Rhodes Piano",
	           "Celesta",
	           "Hammond Organ",
	           "Digital Organ",
	           "Church Organ",
	           "Violin",
	           "Cello",
	           "Fiddle",
	           "Digital Strings",
	           "Pizzicato",
	           "Trumpet",
	           "French Horn",
	           "Tuba",
	           "Flute",
	           "Piccolo",
	           "Pan Flute",
	           "Ocarina",
	           "Clarinet",
	           "Oboe",
	           "Choir",
	           "Harp",
	           "Acoustic Guitar",
	           "Kalimba",
	           "Marimba",
	           "Vibraphone",
	           "Glockenspiel",
	           "Music Box",
	           "Mallet"}},
	         {"Timbre",
	          {"Warm",          "Bright",   "Wide",          "Airy",       "Thick",   "Rich",       "Tight",
	           "Full",          "Gritty",   "Clean",         "Retro",      "Saw",     "Crisp",      "Focused",
	           "Metallic",      "Chiptune", "Dark",          "303",        "Shiny",   "Analog",     "Present",
	           "Sparkly",       "Ambient",  "Soft",          "Smooth",     "Cold",    "Buzzy",      "Deep",
	           "Formant Vocal", "Round",    "Punchy",        "Nasal",      "Vintage", "Growl",      "Breathy",
	           "Glassy",        "Noisy",    "Synthetic Vox", "Bitcrushed", "Dreamy",  "Silky",      "Overdriven",
	           "Fat",           "Near",     "Intimate",      "Spacey",     "Square",  "Pulse Wave", "Digital",
	           "Acid",          "Dubstep",  "Small"}},
	         {"Notation",
	          {"Chord Progression",
	           "Alternating Chord Progression",
	           "Melody",
	           "Top Melody",
	           "Complex Melody",
	           "Complex Arp Melody",
	           "Arp",
	           "Complex Arp",
	           "Triplets",
	           "Simple",
	           "Complex",
	           "Rising",
	           "Falling",
	           "Strummed",
	           "Sustained",
	           "Plucked",
	           "Catchy",
	           "Epic",
	           "Choppy",
	           "Rolling",
	           "Slow Speed",
	           "Fast Speed",
	           "Pitch Bend",
	           "Bassline",
	           "Atmosphere"}},
	         {"FX",
	          {"Low Reverb",
	           "Medium Reverb",
	           "High Reverb",
	           "Plate Reverb",
	           "Low Delay",
	           "Medium Delay",
	           "High Delay",
	           "Ping Pong Delay",
	           "Stereo Delay",
	           "Cross Delay",
	           "Mono Delay",
	           "Low Distortion",
	           "Medium Distortion",
	           "High Distortion",
	           "Low Phaser",
	           "Medium Phaser",
	           "High Phaser",
	           "Phaser",
	           "Bitcrush",
	           "High Bitcrush",
	           "Dry",
	           "Wet"}},
	     },
	     {
	         "Bass, FM Bass, Sub Bass, Acid, Gritty, Wide, Thick, Warm, Overdriven, Bassline, Pitch Bend, 303, Medium "
	         "Delay, Medium Reverb, Low Distortion, Phaser",
	         "Bass, Reese Bass, Wide, Growl, Deep, Thick, Bassline, Sustained, Medium Distortion, Low Reverb",
	         "Sub Bass, Bass, Square, Dark, Digital, Thick, Clean, Simple, Bassline, Choppy",
	         "Synth Bass, 303, Acid, Buzzy, Gritty, Bassline, Fast Speed, Medium Phaser, Medium Reverb",

	         "Synth Lead, Wavetable Synth, Bright, Buzzy, Crisp, Top Melody, Complex, Pitch Bend, Ping Pong Delay, "
	         "Medium Reverb",
	         "Synth Lead, Spacey, Warm, Silky, Smooth, 303, Pitch Bend, Arp, Medium Reverb, Low Distortion",
	         "Synth Lead, FM Synth, Gritty, Acid, Bassline, Pitch Bend, High Phaser, High Reverb",

	         "Pad, Synth, Chord Progression, Rising, Warm, Wide, Silky, Focused, Fat, Near, Sustained, High Reverb",
	         "Pad, Atmosphere, Warm, Soft, Dreamy, Ambient, Spacey, Sustained, High Reverb, Plate Reverb",

	         "Kalimba, Mallet, Sparkly, Metallic, Bright, Airy, Thick, Wide, Overdriven, Alternating Chord "
	         "Progression, Atmosphere, Fast Speed, Medium Reverb",
	         "Rhodes Piano, Warm, Round, Vintage, Smooth, Chord Progression, Sustained, Plate Reverb, Low Delay",
	         "Pluck, Bell, Bright, Glassy, Sparkly, Arp, Triplets, Stereo Delay, Medium Reverb",

	         "Bowed Strings, Cello, Warm, Rich, Intimate, Melody, Slow Speed, Sustained, Plate Reverb",
	         "Fiddle, Bowed Strings, Full, Clean, Spacey, Rich, Rolling, Arp, Fast Speed, Complex, Medium Reverb",
	         "Flute, Pizzicato, Punchy, Present, Nasal, Airy, Melody, Epic, Slow Speed, Medium Reverb",
	         "Trumpet, Warm, Smooth, Silky, Complex Arp Melody, High Reverb, Low Distortion",
	         "Piccolo, Flute, Airy, Music Box, Plucked, Complex Melody, Medium Reverb",

	         "Chiptune, Pulse Wave, Chord Progression, Bright, Retro, Medium Reverb",
	     }},

	    {"audialab-edm-elements",
	     "EDM components with speed controls. Format: [Sound Type], [Modifier], [Phrase], [Speed], [FX]",
	     {
	         {"Sound Types",
	          {"Pluck", "Sine", "Bell", "Bright", "Clean", "Lead", "Square", "Buzzy", "Legato", "Saw", "Warm",
	           "Supersaw", "Synth", "Bass", "Sub", "Punchy", "Pluck Bass"}},
	         {"Modifiers", {"Simple", "Complex", "Epic", "Bounce", "Triplets", "Rising", "Falling", "Catchy", "Dance"}},
	         {"Phrase Types",
	          {"Chord Progression", "Dance Chord Progression", "Top Melody", "Top Catchy Melody", "Top Triplet Melody",
	           "Catchy Melody", "Slow Melody", "Melody", "Arp", "Falling Arp", "Rising Arp", "Bassline", "Riff"}},
	         {"Speed", {"Slow Speed", "Medium Speed", "Fast Speed"}},
	         {"FX",
	          {"Small Reverb", "Medium Reverb", "High Reverb", "Rising Low-Pass", "Falling High-Cut",
	           "Quarter-Beat Gate", "Half-Beat Gate"}},
	     },
	     {
	         "Pluck, Sine, Bright, Clean, Bell, Chord Progression, Top Catchy Melody, High Reverb",
	         "Sine, Bell, Pluck, Chord Progression, Slow Melody, High Reverb, Rising Low-Pass",
	         "Pluck, Bell, Triplets, Medium Speed, Small Reverb",

	         "Lead, Square, Synth, Buzzy, Legato, Catchy Melody, High Reverb",
	         "Legato, Square, Catchy Melody, High Reverb",
	         "Lead, Square, Buzzy, Bounce, Fast Speed, Quarter-Beat Gate",

	         "Lead, Saw, Synth, Warm, Supersaw, Chord Progression, Top Melody, Rising Low-Pass",
	         "Supersaw, Dance Chord Progression, Top Triplet Melody, Medium Reverb",
	         "Supersaw, Complex, Epic, Arp, Medium Reverb",
	         "Synth, Saw, Fast Speed, Falling Arp, Medium Reverb, Falling High-Cut",

	         "Bass, Punchy, Pluck, Clean, Sub, Sine, Bassline, Medium Speed, Small Reverb",
	         "Sine, Bass, Bounce, Catchy Melody",
	         "Pluck Bass, Riff, Fast Speed, Half-Beat Gate",
	     }},

	    {"rc-infinite-pianos",
	     "Piano performance prompts. Format: [Type], [Modifier], [Phrase], [Tremolo], [Reverb]",
	     {
	         {"Piano Types", {"Grand Piano", "Soft E. Piano", "Medium E. Piano"}},
	         {"Performance",
	          {"simple",           "complex",        "jazzy",         "dance plucky",    "plucky dance",
	           "plucky",           "fast",           "slow",          "smooth",          "low",
	           "rising",           "falling",        "strummed",      "simple strummed", "rising strummed",
	           "complex strummed", "jazzy strummed", "slow strummed", "slow jazzy",      "fast jazzy"}},
	         {"Phrase Types",
	          {"chord progression only",
	           "melody only",
	           "chord progression with top catchy melody",
	           "chord progression with melody",
	           "chord progression with complex melody",
	           "chord progression with smooth melody",
	           "chord progression with jazzy melody",
	           "catchy melody",
	           "complex melody",
	           "complex top melody",
	           "catchy top melody",
	           "top melody",
	           "smooth melody",
	           "smooth catchy melody",
	           "complex catchy melody",
	           "jazzy melody",
	           "plucky dance melody",
	           "dance melody",
	           "top arp melody",
	           "alternating top arp melody",
	           "alternating top melody",
	           "alternating catchy melody",
	           "alternating low melody",
	           "alternating melody",
	           "rising arp melody",
	           "falling arp melody",
	           "slow top melody",
	           "fast top melody",
	           "slow catchy top melody",
	           "fast catchy top melody",
	           "top catchy melody"}},
	         {"Tremolo (E. Piano only)", {"No Tremolo", "Low Tremolo", "Medium Tremolo", "High Tremolo"}},
	         {"Reverb", {"No Reverb", "Low Reverb", "Medium Reverb", "High Reverb", "High Spacey Reverb"}},
	     },
	     {
	         "Grand Piano, jazzy, chord progression with top catchy melody, Medium Reverb",
	         "Grand Piano, slow, chord progression only, Low Reverb",
	         "Grand Piano, complex, chord progression with complex melody, High Spacey Reverb",
	         "Grand Piano, rising, top arp melody, Medium Reverb",
	         "Grand Piano, slow jazzy, chord progression with melody, High Reverb",

	         "Soft E. Piano, smooth, chord progression only, Low Tremolo, Medium Reverb",
	         "Soft E. Piano, complex, chord progression with top catchy melody, Medium Tremolo, High Reverb",
	         "Soft E. Piano, slow, alternating top melody, Low Tremolo, High Spacey Reverb",
	         "Soft E. Piano, jazzy, chord progression with jazzy melody, Medium Tremolo, Medium Reverb",
	         "Soft E. Piano, falling, falling arp melody, Low Tremolo, High Reverb",

	         "Medium E. Piano, dance plucky, alternating top arp melody, Medium Tremolo, High Reverb",
	         "Medium E. Piano, plucky dance, dance melody, Low Tremolo, Medium Reverb",
	         "Medium E. Piano, complex strummed, chord progression with melody, Medium Tremolo, High Reverb",
	         "Medium E. Piano, fast, fast catchy top melody, High Tremolo, High Spacey Reverb",
	         "Medium E. Piano, low, chord progression only, Medium Tremolo, Medium Reverb",
	     }},

	    {"rc-vocal-textures",
	     "Vocal / operatic chord progressions. Trained only on [Vocal Type], Chord Progression. Add reverb/FX in post.",
	     {
	         {"Vocal Types", {"Male Vocal Texture", "Female Vocal Texture", "Ensemble Vocal Texture"}},
	         {"Required", {"Chord Progression"}},
	     },
	     {
	         "Male Vocal Texture, Chord Progression",
	         "Female Vocal Texture, Chord Progression",
	         "Ensemble Vocal Texture, Chord Progression",
	     }},

	    {"sao-instrumental",
	     "Modern instrumental stems. Format: [Genre], [Main Inst], [Secondary], [Mood], [Contour]",
	     {
	         {"Genres",
	          {"Cloud Trap", "Melodic Trap", "Lofi Jazz Rap", "Neo-Soul", "Alternative Rock", "British Pop Rock",
	           "Hard Rock", "British 60s Oldies"}},
	         {"Instruments",
	          {"nostalgic piano", "plucked bass", "synth bells", "vocal adlibs", "electric guitar riffs",
	           "deep sub bass", "airy vocal pads", "live bass", "soft Rhodes keys", "warm analog grooves"}},
	         {"Moods",
	          {"Dark", "melancholic", "laid back", "chill", "smooth", "seductive", "romantic", "energetic", "raw",
	           "contemplative", "moody", "boomy"}},
	     },
	     {
	         "Cloud Trap, nostalgic piano, plucked bass, dreamy, melancholic",
	         "Neo-Soul, soft Rhodes keys, live bass, smooth, seductive",
	         "Lofi Jazz Rap, soft Rhodes keys, plucked bass, laid back, chill",
	         "Alternative Rock, electric guitar riffs, warm analog grooves, energetic, raw",
	         "Melodic Trap, synth bells, deep sub bass, dark, moody",
	         "British 60s Oldies, vocal adlibs, airy vocal pads, romantic, contemplative",
	     }},

	    {"stablebeat",
	     "Trap drum and percussion engine. Format: [Solo/Full Beat], Instruments: drum, [Style], [Timbre], [Density]",
	     {
	         {"Format", {"Solo", "Full Beat"}},
	         {"Required", {"Instruments: drum"}},
	         {"Styles",
	          {"cloud trap beat", "melodic trap beat", "boom bap", "jazzy chillhop", "industrial hip-hop", "r&b beat"}},
	         {"Timbre",
	          {"boomy bass", "deep sub", "punchy snare", "crisp hi-hats", "dirty piano loop", "distorted kick",
	           "industrial metallic percussion"}},
	         {"Rhythmic", {"driving 4/4 beat", "syncopated rhythm", "off-beat patterns", "boomy", "rhythmic density"}},
	     },
	     {
	         "Full Beat, Instruments: drum, cloud trap beat, boomy bass, syncopated rhythm",
	         "Solo, Instruments: drum, boom bap, dirty piano loop, driving 4/4 beat",
	         "Full Beat, Instruments: drum, industrial hip-hop, distorted kick, industrial metallic percussion",
	         "Solo, Instruments: drum, jazzy chillhop, crisp hi-hats, off-beat patterns",
	         "Full Beat, Instruments: drum, melodic trap beat, deep sub, punchy snare",
	         "Solo, Instruments: drum, r&b beat, boomy, rhythmic density",
	     }},

	    {"gluten-v1",
	     "Loopable musical phrases. Format: pipe-separated. NO BPM/Key.",
	     {
	         {"Genres", {"Trap", "Melodic Trap", "Wavy Trap", "Hip-Hop", "Boom Bap", "Pop", "Ambient"}},
	         {"Instruments", {"Piano", "Synth Pad", "Synth Lead", "808 Bass", "Bells", "Strings", "Ambient Pads"}},
	         {"Moods",
	          {"Melancholic", "Reflective", "Catchy", "Smooth", "Epic", "Dark", "Atmospheric", "Building", "Ethereal",
	           "Sad", "Heavy", "Driving", "Punchy", "Rhythmic"}},
	         {"Tempo", {"Slow", "Medium", "Fast"}},
	         {"Templates", {"Format: Solo | Genre:  | Sub-Genre:  | Instruments:  | Moods:  | Styles:  | Tempo: "}},
	     },
	     {
	         "Format: Solo | Genre: Trap | Sub-Genre: Melodic Trap | Instruments: Piano, Synth Pad | Moods: "
	         "Melancholic | Styles: Catchy, Smooth | Tempo: Medium",
	         "Format: Solo | Genre: Ambient | Sub-Genre: Ambient | Instruments: Synth Pad, Strings | Moods: "
	         "Atmospheric, Ethereal | Styles: Building | Tempo: Slow",
	         "Format: Solo | Genre: Hip-Hop | Sub-Genre: Boom Bap | Instruments: Piano, 808 Bass | Moods: Sad | "
	         "Styles: Smooth | Tempo: Medium",
	         "Format: Solo | Genre: Pop | Sub-Genre: Pop | Instruments: Synth Lead, Bells | Moods: Catchy, Driving | "
	         "Styles: Punchy | Tempo: Fast",
	         "Format: Solo | Genre: Trap | Sub-Genre: Wavy Trap | Instruments: Bells, Synth Lead | Moods: Reflective, "
	         "Atmospheric | Styles: Ethereal | Tempo: Slow",
	     }},
	};
	return models;
}

const PromptModelDefinitions::ModelInfo *PromptModelDefinitions::getModel(const juce::String &modelName)
{
	for (const auto &m : getAllModels())
		if (m.modelName == modelName)
			return &m;
	return nullptr;
}