#include "PromptModelDefinitions.h"

const std::vector<PromptModelDefinitions::ModelInfo> &PromptModelDefinitions::getAllModels()
{
	static std::vector<ModelInfo> models = {
	    {"stable-audio-open-1.0",
	     "Natural language descriptive prompts. Format: [Style/Genre], [Key Elements], [Mood], [Details]",
	     {
	         {"Genres",
	          {"techno", "house", "trap", "drum and bass", "ambient", "hip-hop", "jungle", "dub", "industrial",
	           "hardcore", "breakbeat", "lo-fi", "synthwave", "psychedelic"}},
	         {"Elements",
	          {"kick drum loop", "bassline", "hi-hat loop", "snare pattern", "percussion loop", "synth melody", "lead",
	           "pad", "arpeggio", "vocal chops", "noise stabs"}},
	         {"Moods",
	          {"dark", "warm", "aggressive", "chill", "melancholic", "euphoric", "dreamy", "haunting", "uplifting",
	           "moody", "raw", "ethereal"}},
	         {"Qualities",
	          {"solo", "isolated", "dry", "rhythmic", "monophonic", "driving", "rolling", "punchy", "crisp", "deep",
	           "warm", "distorted", "metallic", "squelchy"}},
	         {"Negatives", {"no background elements", "no pads", "no melody", "no accompaniment", "no rhythm"}},
	     },
	     {
	         "deep dub kick loop, solo kick pattern, sub-heavy 4/4, dry, no background",
	         "psychedelic ambient flute melody, solo flute, ethereal phrasing, dry, no rhythm",
	         "rolling jungle break loop, solo amen percussion, chopped, dry, isolated",
	         "warm analog lead melody, solo monophonic synth, soft saw wave, dry",
	         "industrial noise stabs, solo distorted hits, rhythmic, dry, no melodic content",
	         "minimal techno hi-hat loop, solo metallic hi-hats, off-beat, dry, isolated",
	     }},

	    {"stable-audio-3-medium",
	     "Universal Multi-mode engine. For full tracks use 'TrackType: Music' (+ 'VocalType: Instrumental' for "
	     "coherence). Stems/solo use 'TrackType: Instrument' (+ 'Format: Solo/Duo'). FX use 'TrackType: SFX'. Music "
	     "mode benefits from BPM (e.g. '120 BPM'); Instrument/SFX usually NO BPM/Key. Init/inpaint: tune "
	     "init_noise_level (0.3-0.6) for timbre vs style transfer.",
	     {
	         {"Track Types & Modes",
	          {"TrackType: Music", "TrackType: Instrument", "TrackType: SFX", "VocalType: Instrumental", "Format: Solo",
	           "Format: Duo", "Format: Trio", "Format: Full Band", "Format: Ensemble"}},
	         {"Mood & Energy", {"euphoric",       "melancholic", "nostalgic",  "triumphant", "ominous",   "eerie",
	                            "hypnotic",       "meditative",  "aggressive", "menacing",   "playful",   "whimsical",
	                            "dreamy",         "ethereal",    "brooding",   "tense",      "uplifting", "bittersweet",
	                            "claustrophobic", "expansive",   "intimate",   "epic",       "sleazy",    "frantic",
	                            "serene",         "psychedelic", "dystopian",  "sacred",     "feverish",  "deadpan"}},
	         {"Global Genres", {"Blues",         "Rock",
	                            "Metal",         "Punk",
	                            "Jazz",          "Electronic",
	                            "Hip-Hop",       "Urban",
	                            "Pop",           "Classical",
	                            "Avant-Garde",   "Experimental",
	                            "Folk",          "World Music",
	                            "Cinematic",     "Ambient",
	                            "Soundtrack",    "Spoken Word Backing",
	                            "Library Music", "Production Music"}},
	         {"Electronic & Dance Sub-Genres",
	          {"House",
	           "Deep House",
	           "Tech House",
	           "Acid House",
	           "Progressive House",
	           "Afro House",
	           "Microhouse",
	           "Techno",
	           "Minimal Techno",
	           "Industrial Techno",
	           "Dub Techno",
	           "Hard Techno",
	           "Detroit Techno",
	           "Drum and Bass",
	           "Liquid DnB",
	           "Neurofunk",
	           "Jump Up",
	           "Jungle",
	           "Ragga Jungle",
	           "Breakbeat",
	           "Big Beat",
	           "Breakcore",
	           "Dubstep",
	           "Riddim",
	           "Future Garage",
	           "Garage",
	           "UKG",
	           "2-Step",
	           "Grime",
	           "Trance",
	           "Psytrance",
	           "Goa Trance",
	           "Hardstyle",
	           "Gabber",
	           "Hardcore",
	           "Synthwave",
	           "Darksynth",
	           "Chiptune",
	           "Glitch Hop",
	           "IDM",
	           "Drill and Bass",
	           "Vaporwave",
	           "Future Funk",
	           "Downtempo",
	           "Trip Hop",
	           "Electro Swing",
	           "Electro",
	           "EBM",
	           "Witch House",
	           "Hyperpop",
	           "Footwork",
	           "Juke",
	           "Bass Music",
	           "Wave",
	           "Ambient Techno",
	           "Lo-fi House",
	           "Hardgroove",
	           "Modular Patch",
	           "Eurodance"}},
	         {"Rock, Metal & Punk Sub-Genres", {"Classic Rock",     "Psychedelic Rock", "Prog Rock",     "Hard Rock",
	                                            "Heavy Metal",      "Thrash Metal",     "Death Metal",   "Black Metal",
	                                            "Doom Metal",       "Sludge",           "Stoner Rock",   "Djent",
	                                            "Math Rock",        "Post-Rock",        "Post-Metal",    "Grunge",
	                                            "Alternative Rock", "Indie Rock",       "Garage Rock",   "Surf Rock",
	                                            "Punk Rock",        "Hardcore Punk",    "Post-Hardcore", "Crust Punk",
	                                            "D-Beat",           "Post-Punk",        "Goth Rock",     "Shoegaze",
	                                            "Dream Pop",        "Noise Rock",       "Drone Metal",   "Funeral Doom",
	                                            "Blackgaze",        "Industrial Metal", "Nu Metal",      "Metalcore",
	                                            "Grindcore",        "Krautrock",        "Space Rock",    "Ska"}},
	         {"Urban, Hip-Hop & R&B Sub-Genres",
	          {"Boom Bap",
	           "East Coast Hip-Hop",
	           "West Coast G-Funk",
	           "Dirty South",
	           "Trap",
	           "Cloud Trap",
	           "Drill",
	           "UK Drill",
	           "Phonk",
	           "Memphis Rap",
	           "Lofi Hip-Hop",
	           "Jazz Rap",
	           "Abstract Hip-Hop",
	           "Plugg",
	           "R&B",
	           "Neo-Soul",
	           "Alt R&B",
	           "Funk",
	           "P-Funk",
	           "Disco",
	           "Nu-Disco",
	           "Reggae",
	           "Roots Reggae",
	           "Dancehall",
	           "Dub",
	           "Reggaeton",
	           "Afroswing",
	           "Amapiano",
	           "Gqom",
	           "Baile Funk"}},
	         {"Jazz, Blues & Roots Sub-Genres",
	          {"Delta Blues", "Chicago Blues", "Texas Blues",    "Ragtime",    "Dixieland",     "Swing Jazz",
	           "Bebop",       "Hard Bop",      "Cool Jazz",      "Modal Jazz", "Free Jazz",     "Spiritual Jazz",
	           "Jazz Fusion", "Nu Jazz",       "Lofi Jazz",      "Gypsy Jazz", "Bossa Jazz",    "Bluegrass",
	           "Americana",   "Country",       "Outlaw Country", "Honky Tonk", "Western Swing", "Cajun",
	           "Zydeco",      "Gospel",        "Spirituals"}},
	         {"World, Ethnic & Folk Regional",
	          {"Afrobeat",
	           "Highlife",
	           "Kuduro",
	           "Soukous",
	           "Ethio-Jazz",
	           "Desert Blues",
	           "Salsa",
	           "Mambo",
	           "Merengue",
	           "Bossa Nova",
	           "Samba",
	           "Choro",
	           "Forro",
	           "Flamenco",
	           "Fado",
	           "Celtic Folk",
	           "Traditional Irish",
	           "Nordic Folk",
	           "Gypsy Jazz",
	           "Klezmer",
	           "Balkan Brass",
	           "Indian Classical",
	           "Carnatic",
	           "Hindustani",
	           "Bhangra",
	           "Gamelan",
	           "Andean Folk",
	           "Mariachi",
	           "Cumbia",
	           "Sufi Qawwali",
	           "Traditional Chinese",
	           "Tuvan Throat Singing",
	           "Mbalax",
	           "Rebetiko",
	           "Tarab",
	           "Joik"}},
	         {"Classical, Cinematic & Orchestral",
	          {"Baroque",          "Classical Era",    "Romantic Era",     "Impressionism",
	           "Expressionism",    "Minimalism",       "Modern Classical", "Neoclassical",
	           "Serialism",        "Musique Concrete", "Spectral Music",   "Drone",
	           "Epic Cinematic",   "Dystopian Sci-Fi", "Horror Ambient",   "Noir Jazz Score",
	           "Western Score",    "Trailer Music",    "Orchestral Brass", "Chamber Strings",
	           "Solo Piano Score", "Choral Sacred",    "Tone Poem",        "Fanfare"}},
	         {"Acoustic & Ethnic Instruments",
	          {"acoustic guitar",
	           "resonator",
	           "cigar box guitar",
	           "12-string guitar",
	           "nylon classical guitar",
	           "banjo",
	           "mandolin",
	           "fiddle",
	           "ukulele",
	           "upright bass",
	           "harp",
	           "concertina",
	           "accordion",
	           "harmonica",
	           "kora",
	           "sitar",
	           "oud",
	           "shakuhachi",
	           "tin whistle",
	           "didgeridoo",
	           "hang drum",
	           "kalimba",
	           "marimba",
	           "balalaika",
	           "bouzouki",
	           "erhu",
	           "guzheng",
	           "bagpipes",
	           "pan flute",
	           "ocarina",
	           "lute",
	           "hurdy-gurdy",
	           "saz",
	           "tar",
	           "pipa",
	           "berimbau",
	           "jaw harp",
	           "dulcimer",
	           "zither",
	           "nyckelharpa",
	           "santur",
	           "duduk",
	           "ngoni",
	           "mbira",
	           "shamisen",
	           "koto",
	           "bansuri",
	           "ney"}},
	         {"Electric, Keys & Synth Instruments",
	          {"electric guitar riff",
	           "seven-string guitar",
	           "eight-string guitar",
	           "baritone guitar",
	           "overdriven bassline",
	           "slap bass",
	           "fretless bass",
	           "grand piano",
	           "upright piano",
	           "prepared piano",
	           "rhodes keys",
	           "wurlitzer",
	           "hammond organ",
	           "pipe organ",
	           "clavinet",
	           "mellotron",
	           "harpsichord",
	           "celesta",
	           "monophonic lead",
	           "polyphonic pad",
	           "modular arp",
	           "303 acid bass",
	           "reese bass",
	           "sub-bass growl",
	           "FM bass",
	           "supersaw lead",
	           "wavetable pluck",
	           "chiptune pulse wave",
	           "theremin",
	           "laser harp",
	           "ondes martenot",
	           "vocoder pad",
	           "formant synth",
	           "granular drone",
	           "additive bell",
	           "PPG-style wavetable",
	           "analog brass stab",
	           "string machine",
	           "detuned saw stack"}},
	         {"Drums, Percussion & Grooves",
	          {"acoustic drum-kit",
	           "brushed snare",
	           "snare rimshots",
	           "closed hi-hats",
	           "open cymbal sizzle",
	           "linn drum",
	           "808 sub kick",
	           "909 drum loop",
	           "707 drum machine",
	           "606 drum machine",
	           "amen break beat",
	           "think break",
	           "funky drummer break",
	           "taiko drum",
	           "djembe",
	           "congas",
	           "bongos",
	           "timbales",
	           "darbuka",
	           "tabla",
	           "dholak",
	           "cajon",
	           "shaker loop",
	           "tambourine",
	           "cowbell",
	           "woodblock",
	           "guiro",
	           "castanets",
	           "gong",
	           "frame drum",
	           "udu",
	           "cuica",
	           "surdo",
	           "tar drum",
	           "bodhran",
	           "handclaps",
	           "finger snaps",
	           "rototoms",
	           "gamelan gongs",
	           "steel pan",
	           "junkyard percussion",
	           "glitched breakbeat",
	           "vintage jazz kit brushed",
	           "tight 70s funk break kit",
	           "dry close-mic rock kit",
	           "roomy 60s soul kit",
	           "gospel live drum kit",
	           "bonham-style big room kit",
	           "motown backbeat kit with tambourine",
	           "new orleans second line kit",
	           "surf rock reverb kit",
	           "metal double-kick kit",
	           "thrash metal blast-beat kit",
	           "death metal blast-beat kit",
	           "black metal raw lo-fi kit",
	           "doom metal slow pounding kit",
	           "sludge metal heavy kit",
	           "djent tight-trigger kit",
	           "metalcore breakdown kit",
	           "punk rock fast snare kit",
	           "hardcore punk d-beat kit",
	           "garage rock raw kit",
	           "stoner rock fuzzy room kit",
	           "post-rock dynamic swell kit",
	           "prog rock odd-meter kit",
	           "grunge loose room kit",
	           "classic rock dry kit",
	           "hard rock arena kit"
	           "808 trap kit",
	           "909 techno kit",
	           "707 electro kit",
	           "606 acid kit",
	           "linn drum 80s kit",
	           "breakbeat chopped amen kit",
	           "jungle ragga drum kit",
	           "dnb think-break kit",
	           "lo-fi dusty boom bap kit",
	           "glitchy IDM percussion kit",
	           "gabber distorted kick kit",
	           "house clap-and-hat kit",
	           "dub techno minimal kit",
	           "footwork rapid hi-hat kit",
	           "phonk cowbell trap kit",
	           "drill sliding 808 kit",
	           "reggaeton dembow kit",
	           "afrobeat live percussion kit",
	           "latin salsa timbale kit",
	           "samba batucada kit",
	           "taiko ensemble kit",
	           "tabla and dholak kit",
	           "djembe and congas kit",
	           "darbuka and frame drum kit",
	           "gamelan gong kit",
	           "steel pan percussion kit",
	           "industrial metal-clang kit",
	           "junkyard found-percussion kit",
	           "glitched buffer-stutter kit",
	           "cinematic trailer hit kit",
	           "brushed rimshot ballad kit",
	           "hand-clap and finger-snap kit"}},
	         {"Sound Design, Textures & FX",
	          {"sub-bass boom",
	           "sub drop",
	           "electronic riser",
	           "white noise swoop",
	           "downlifter",
	           "industrial door slam",
	           "metal scrape",
	           "tape-stop effect",
	           "granular glitch",
	           "buffer stutter",
	           "modular bleeps",
	           "laser shot",
	           "vinyl crackle",
	           "analog tape hiss",
	           "field recording hum",
	           "reverse cymbal swell",
	           "subsonic explosion",
	           "impact transient",
	           "mechanical click",
	           "servo whirr",
	           "atmospheric drone",
	           "sci-fi telemetry",
	           "cinematic braam",
	           "sub-bass rumble",
	           "geiger ticks",
	           "clock ticking",
	           "glass shatter",
	           "wind howl",
	           "data corruption burst",
	           "spectral freeze",
	           "feedback howl",
	           "contact mic creak",
	           "radio static sweep",
	           "granular rain",
	           "tonal feedback drone",
	           "pitch-bent siren",
	           "vinyl rewind",
	           "dial-up modem screech",
	           "ghostly choir wash",
	           "insect swarm texture"}},
	         {"Acoustics, Production & Pedals",
	          {"dry",
	           "isolated",
	           "close mic",
	           "room acoustics",
	           "cavernous reverb",
	           "massive hall reverb",
	           "plate reverb",
	           "spring reverb",
	           "shimmer reverb",
	           "gated reverb",
	           "convolution IR",
	           "slapback delay",
	           "ping pong delay",
	           "tape delay",
	           "dub siren delay",
	           "high-gain distortion",
	           "fuzz",
	           "tube saturation",
	           "bitcrushed",
	           "sample-rate reduction",
	           "lo-fi warmth",
	           "stereo chorus",
	           "phaser sweeps",
	           "flanger",
	           "wah-wah pedal",
	           "ring modulation",
	           "tremolo",
	           "vibrato",
	           "auto-pan",
	           "sidechain pumping",
	           "tape wow and flutter",
	           "vintage ribbon mic",
	           "binaural recording",
	           "mid-side widening",
	           "mono summed",
	           "telephone EQ",
	           "megaphone",
	           "underwater filter",
	           "VHS degradation",
	           "analog gear warmth"}},
	     },
	     {
	         "TrackType: Music, VocalType: Instrumental, a triumphant UK bass tech-house tune, pumping "
	         "four-to-the-floor "
	         "kick, syncopated 808 bass, gliding emotional synth leads building to a euphoric gospel piano drop",
	         "TrackType: Music, VocalType: Instrumental, a nostalgic alt-pop ballad instrumental, infectious synth "
	         "bass"
	         "tightly tuned acoustic drums, dreamy VHS-tape synths, subtle indie guitars, brooding and melancholic",
	         "TrackType: Music, VocalType: Instrumental, a 70s TV-theme funk instrumental, lightly strummed rhythm "
	         "guitar, "
	         "flanger-effected lead phrases, close-mic'd electric piano, swung old-school drums, warm analog tape",
	         "TrackType: Music, VocalType: Instrumental, a dystopian sci-fi cinematic cue, low orchestral drone, "
	         "industrial percussion hits, granular synth textures, slow tension build, massive hall reverb",
	         "TrackType: Music, VocalType: Instrumental, a hypnotic dub techno track, deep sub-bass, dub-delayed chord "
	         "stabs, crackling vinyl texture, minimal shaker groove, cavernous space",
	         "TrackType: Music, VocalType: Instrumental, a frantic ragga jungle roller, chopped amen break, sub-heavy "
	         "reese bass, dub siren stabs, dark and feverish",
	         "TrackType: Music, VocalType: Instrumental, a serene modal acoustic piece, fingerpicked nylon guitar, "
	         "breathy bansuri flute, hang drum pulse, intimate room acoustics, meditative, rubato free time",
	         "TrackType: Music, VocalType: Instrumental, a sludgy stoner-doom riff cycle, downtuned baritone guitar, "
	         "fuzz bass, slow pounding drums, cavernous and menacing, half-time feel",
	         "TrackType: Music, VocalType: Instrumental, an ethio-jazz fusion groove, swirling Wurlitzer, modal sax "
	         "phrases, loose swung drums, warm analog gear, sleazy and hypnotic",
	         "TrackType: Music, VocalType: Instrumental, a melancholic ambient drone, slow shifting wavetable pads, "
	         "granular field-recording rain, distant tonal feedback, expansive and serene",

	         "TrackType: Instrument, Format: Solo, a raw delta blues slide guitar riff, resonator acoustic guitar, "
	         "dusty vintage tone, fingerpicked, dry",
	         "TrackType: Instrument, Format: Solo, an aggressive heavy metal rhythm guitar riff, seven-string guitar, "
	         "chugging palm mutes, high-gain distortion",
	         "TrackType: Instrument, Format: Solo, a hypnotic West African kora melody, intricate plucked string "
	         "patterns, bright resonant wooden tones, dry",
	         "TrackType: Instrument, Format: Solo, a soulful Japanese shakuhachi flute melody, breathy articulation, "
	         "organic pitch inflections, cinematic zen temple acoustics",
	         "TrackType: Instrument, Format: Solo, a heavy neurobass growl loop, modulated wavetable synthesis, "
	         "aggressive tearing textures, sub-bass pressure, dry",
	         "TrackType: Instrument, Format: Solo, a squelchy acid 303 synth bassline, resonant filter sweeps, "
	         "aggressive analog texture, driving monophonic sequence, dry",
	         "TrackType: Instrument, Format: Solo, dark dystopian cinematic pad, low drone foundation, sweeping "
	         "high-frequency harmonics, tension building, massive hall reverb",
	         "TrackType: Instrument, Format: Solo, an Armenian duduk lament, breathy double-reed tone, mournful "
	         "microtonal bends, intimate close-mic, cavernous reverb tail",
	         "TrackType: Instrument, Format: Duo, a gypsy jazz guitar and upright bass duo, rapid nylon-string runs, "
	         "walking bassline, swung manouche feel, warm room acoustics",
	         "TrackType: Instrument, Format: Solo, a prepared piano pattern, muted metallic resonances, percussive "
	         "damped strings, minimalist repetition, dry close-mic",
	         "TrackType: Instrument, Format: Solo, a haunting solo cello melody, melancholic romantic-era phrasing, "
	         "expressive vibrato, intimate room acoustics",
	         "TrackType: Instrument, Format: Solo, a lofi jazz rhodes chord progression, warm vinyl crackle, soft "
	         "tremolo, nostalgic laid-back vibe",

	         "TrackType: SFX, a massive cinematic sub-bass boom, deep sub-sonic explosion drop, long decaying low-end "
	         "tail, transient impact",
	         "TrackType: SFX, a heavy industrial metal door slamming shut, fast decay, mechanical lock click, recorded "
	         "in a dead concrete room",
	         "TrackType: SFX, a glitchy digital transition, tape-stop effect artifact, pitch and speed dropping "
	         "simultaneously, grinding into a sub frequency",
	         "TrackType: SFX, a cinematic sci-fi braam, distorted low brass layered with analog synth growl, massive "
	         "scale, ominous trailer transient",
	         "TrackType: SFX, a dial-up modem screech recorded through a telephone EQ, harsh digital handshake "
	         "artifacts, lo-fi degraded fidelity, short decay",
	         "TrackType: SFX, a granular rain texture morphing into an insect swarm, evolving spectral motion, eerie "
	         "binaural field recording, long evolving tail",
	     }},

	    {"foundation-1",
	     "Structured tags. Format: [Family], [Sub-Family], [Timbre], [Notation], [FX]. Comma-separated.",
	     {
	         {"Families",
	          {"Synth", "Keys", "Bass", "Bowed Strings", "Mallet", "Wind", "Guitar", "Brass", "Vocal",
	           "Plucked Strings"}},
	         {"Sub-Families",
	          {"Synth Lead",
	           "Synth Bass",
	           "FM Synth",
	           "FM Bass",
	           "Wavetable Synth",
	           "Wavetable Bass",
	           "Supersaw",
	           "Reese Bass",
	           "Sub Bass",
	           "Electric Bass",
	           "Pad",
	           "Atmosphere",
	           "Texture",
	           "Bell",
	           "Pluck",
	           "Grand Piano",
	           "Digital Piano",
	           "Rhodes Piano",
	           "Celesta",
	           "Hammond Organ",
	           "Digital Organ",
	           "Church Organ",
	           "Violin",
	           "Cello",
	           "Fiddle",
	           "Digital Strings",
	           "Pizzicato",
	           "Trumpet",
	           "French Horn",
	           "Tuba",
	           "Flute",
	           "Piccolo",
	           "Pan Flute",
	           "Ocarina",
	           "Clarinet",
	           "Oboe",
	           "Choir",
	           "Harp",
	           "Acoustic Guitar",
	           "Kalimba",
	           "Marimba",
	           "Vibraphone",
	           "Glockenspiel",
	           "Music Box",
	           "Mallet"}},
	         {"Timbre",
	          {"Warm",          "Bright",   "Wide",          "Airy",       "Thick",   "Rich",       "Tight",
	           "Full",          "Gritty",   "Clean",         "Retro",      "Saw",     "Crisp",      "Focused",
	           "Metallic",      "Chiptune", "Dark",          "303",        "Shiny",   "Analog",     "Present",
	           "Sparkly",       "Ambient",  "Soft",          "Smooth",     "Cold",    "Buzzy",      "Deep",
	           "Formant Vocal", "Round",    "Punchy",        "Nasal",      "Vintage", "Growl",      "Breathy",
	           "Glassy",        "Noisy",    "Synthetic Vox", "Bitcrushed", "Dreamy",  "Silky",      "Overdriven",
	           "Fat",           "Near",     "Intimate",      "Spacey",     "Square",  "Pulse Wave", "Digital",
	           "Acid",          "Dubstep",  "Small"}},
	         {"Notation",
	          {"Chord Progression",
	           "Alternating Chord Progression",
	           "Melody",
	           "Top Melody",
	           "Complex Melody",
	           "Complex Arp Melody",
	           "Arp",
	           "Complex Arp",
	           "Triplets",
	           "Simple",
	           "Complex",
	           "Rising",
	           "Falling",
	           "Strummed",
	           "Sustained",
	           "Plucked",
	           "Catchy",
	           "Epic",
	           "Choppy",
	           "Rolling",
	           "Slow Speed",
	           "Fast Speed",
	           "Pitch Bend",
	           "Bassline",
	           "Atmosphere"}},
	         {"FX",
	          {"Low Reverb",
	           "Medium Reverb",
	           "High Reverb",
	           "Plate Reverb",
	           "Low Delay",
	           "Medium Delay",
	           "High Delay",
	           "Ping Pong Delay",
	           "Stereo Delay",
	           "Cross Delay",
	           "Mono Delay",
	           "Low Distortion",
	           "Medium Distortion",
	           "High Distortion",
	           "Low Phaser",
	           "Medium Phaser",
	           "High Phaser",
	           "Phaser",
	           "Bitcrush",
	           "High Bitcrush",
	           "Dry",
	           "Wet"}},
	     },
	     {
	         "Bass, FM Bass, Sub Bass, Acid, Gritty, Wide, Thick, Warm, Overdriven, Bassline, Pitch Bend, 303, Medium "
	         "Delay, Medium Reverb, Low Distortion, Phaser",
	         "Bass, Reese Bass, Wide, Growl, Deep, Thick, Bassline, Sustained, Medium Distortion, Low Reverb",
	         "Sub Bass, Bass, Square, Dark, Digital, Thick, Clean, Simple, Bassline, Choppy",
	         "Synth Bass, 303, Acid, Buzzy, Gritty, Bassline, Fast Speed, Medium Phaser, Medium Reverb",

	         "Synth Lead, Wavetable Synth, Bright, Buzzy, Crisp, Top Melody, Complex, Pitch Bend, Ping Pong Delay, "
	         "Medium Reverb",
	         "Synth Lead, Spacey, Warm, Silky, Smooth, 303, Pitch Bend, Arp, Medium Reverb, Low Distortion",
	         "Synth Lead, FM Synth, Gritty, Acid, Bassline, Pitch Bend, High Phaser, High Reverb",

	         "Pad, Synth, Chord Progression, Rising, Warm, Wide, Silky, Focused, Fat, Near, Sustained, High Reverb",
	         "Pad, Atmosphere, Warm, Soft, Dreamy, Ambient, Spacey, Sustained, High Reverb, Plate Reverb",

	         "Kalimba, Mallet, Sparkly, Metallic, Bright, Airy, Thick, Wide, Overdriven, Alternating Chord "
	         "Progression, Atmosphere, Fast Speed, Medium Reverb",
	         "Rhodes Piano, Warm, Round, Vintage, Smooth, Chord Progression, Sustained, Plate Reverb, Low Delay",
	         "Pluck, Bell, Bright, Glassy, Sparkly, Arp, Triplets, Stereo Delay, Medium Reverb",

	         "Bowed Strings, Cello, Warm, Rich, Intimate, Melody, Slow Speed, Sustained, Plate Reverb",
	         "Fiddle, Bowed Strings, Full, Clean, Spacey, Rich, Rolling, Arp, Fast Speed, Complex, Medium Reverb",
	         "Flute, Pizzicato, Punchy, Present, Nasal, Airy, Melody, Epic, Slow Speed, Medium Reverb",
	         "Trumpet, Warm, Smooth, Silky, Complex Arp Melody, High Reverb, Low Distortion",
	         "Piccolo, Flute, Airy, Music Box, Plucked, Complex Melody, Medium Reverb",

	         "Chiptune, Pulse Wave, Chord Progression, Bright, Retro, Medium Reverb",
	     }},

	    {"audialab-edm-elements",
	     "EDM components with speed controls. Format: [Sound Type], [Modifier], [Phrase], [Speed], [FX]",
	     {
	         {"Sound Types",
	          {"Pluck", "Sine", "Bell", "Bright", "Clean", "Lead", "Square", "Buzzy", "Legato", "Saw", "Warm",
	           "Supersaw", "Synth", "Bass", "Sub", "Punchy", "Pluck Bass"}},
	         {"Modifiers", {"Simple", "Complex", "Epic", "Bounce", "Triplets", "Rising", "Falling", "Catchy", "Dance"}},
	         {"Phrase Types",
	          {"Chord Progression", "Dance Chord Progression", "Top Melody", "Top Catchy Melody", "Top Triplet Melody",
	           "Catchy Melody", "Slow Melody", "Melody", "Arp", "Falling Arp", "Rising Arp", "Bassline", "Riff"}},
	         {"Speed", {"Slow Speed", "Medium Speed", "Fast Speed"}},
	         {"FX",
	          {"Small Reverb", "Medium Reverb", "High Reverb", "Rising Low-Pass", "Falling High-Cut",
	           "Quarter-Beat Gate", "Half-Beat Gate"}},
	     },
	     {
	         "Pluck, Sine, Bright, Clean, Bell, Chord Progression, Top Catchy Melody, High Reverb",
	         "Sine, Bell, Pluck, Chord Progression, Slow Melody, High Reverb, Rising Low-Pass",
	         "Pluck, Bell, Triplets, Medium Speed, Small Reverb",

	         "Lead, Square, Synth, Buzzy, Legato, Catchy Melody, High Reverb",
	         "Legato, Square, Catchy Melody, High Reverb",
	         "Lead, Square, Buzzy, Bounce, Fast Speed, Quarter-Beat Gate",

	         "Lead, Saw, Synth, Warm, Supersaw, Chord Progression, Top Melody, Rising Low-Pass",
	         "Supersaw, Dance Chord Progression, Top Triplet Melody, Medium Reverb",
	         "Supersaw, Complex, Epic, Arp, Medium Reverb",
	         "Synth, Saw, Fast Speed, Falling Arp, Medium Reverb, Falling High-Cut",

	         "Bass, Punchy, Pluck, Clean, Sub, Sine, Bassline, Medium Speed, Small Reverb",
	         "Sine, Bass, Bounce, Catchy Melody",
	         "Pluck Bass, Riff, Fast Speed, Half-Beat Gate",
	     }},

	    {"rc-infinite-pianos",
	     "Piano performance prompts. Format: [Type], [Modifier], [Phrase], [Tremolo], [Reverb]",
	     {
	         {"Piano Types", {"Grand Piano", "Soft E. Piano", "Medium E. Piano"}},
	         {"Performance",
	          {"simple",           "complex",        "jazzy",         "dance plucky",    "plucky dance",
	           "plucky",           "fast",           "slow",          "smooth",          "low",
	           "rising",           "falling",        "strummed",      "simple strummed", "rising strummed",
	           "complex strummed", "jazzy strummed", "slow strummed", "slow jazzy",      "fast jazzy"}},
	         {"Phrase Types",
	          {"chord progression only",
	           "melody only",
	           "chord progression with top catchy melody",
	           "chord progression with melody",
	           "chord progression with complex melody",
	           "chord progression with smooth melody",
	           "chord progression with jazzy melody",
	           "catchy melody",
	           "complex melody",
	           "complex top melody",
	           "catchy top melody",
	           "top melody",
	           "smooth melody",
	           "smooth catchy melody",
	           "complex catchy melody",
	           "jazzy melody",
	           "plucky dance melody",
	           "dance melody",
	           "top arp melody",
	           "alternating top arp melody",
	           "alternating top melody",
	           "alternating catchy melody",
	           "alternating low melody",
	           "alternating melody",
	           "rising arp melody",
	           "falling arp melody",
	           "slow top melody",
	           "fast top melody",
	           "slow catchy top melody",
	           "fast catchy top melody",
	           "top catchy melody"}},
	         {"Tremolo (E. Piano only)", {"No Tremolo", "Low Tremolo", "Medium Tremolo", "High Tremolo"}},
	         {"Reverb", {"No Reverb", "Low Reverb", "Medium Reverb", "High Reverb", "High Spacey Reverb"}},
	     },
	     {
	         "Grand Piano, jazzy, chord progression with top catchy melody, Medium Reverb",
	         "Grand Piano, slow, chord progression only, Low Reverb",
	         "Grand Piano, complex, chord progression with complex melody, High Spacey Reverb",
	         "Grand Piano, rising, top arp melody, Medium Reverb",
	         "Grand Piano, slow jazzy, chord progression with melody, High Reverb",

	         "Soft E. Piano, smooth, chord progression only, Low Tremolo, Medium Reverb",
	         "Soft E. Piano, complex, chord progression with top catchy melody, Medium Tremolo, High Reverb",
	         "Soft E. Piano, slow, alternating top melody, Low Tremolo, High Spacey Reverb",
	         "Soft E. Piano, jazzy, chord progression with jazzy melody, Medium Tremolo, Medium Reverb",
	         "Soft E. Piano, falling, falling arp melody, Low Tremolo, High Reverb",

	         "Medium E. Piano, dance plucky, alternating top arp melody, Medium Tremolo, High Reverb",
	         "Medium E. Piano, plucky dance, dance melody, Low Tremolo, Medium Reverb",
	         "Medium E. Piano, complex strummed, chord progression with melody, Medium Tremolo, High Reverb",
	         "Medium E. Piano, fast, fast catchy top melody, High Tremolo, High Spacey Reverb",
	         "Medium E. Piano, low, chord progression only, Medium Tremolo, Medium Reverb",
	     }},

	    {"rc-vocal-textures",
	     "Vocal / operatic chord progressions. Trained only on [Vocal Type], Chord Progression. Add reverb/FX in post.",
	     {
	         {"Vocal Types", {"Male Vocal Texture", "Female Vocal Texture", "Ensemble Vocal Texture"}},
	         {"Required", {"Chord Progression"}},
	     },
	     {
	         "Male Vocal Texture, Chord Progression",
	         "Female Vocal Texture, Chord Progression",
	         "Ensemble Vocal Texture, Chord Progression",
	     }},

	    {"sao-instrumental",
	     "Modern instrumental stems. Format: [Genre], [Main Inst], [Secondary], [Mood], [Contour]",
	     {
	         {"Genres",
	          {"Cloud Trap", "Melodic Trap", "Lofi Jazz Rap", "Neo-Soul", "Alternative Rock", "British Pop Rock",
	           "Hard Rock", "British 60s Oldies"}},
	         {"Instruments",
	          {"nostalgic piano", "plucked bass", "synth bells", "vocal adlibs", "electric guitar riffs",
	           "deep sub bass", "airy vocal pads", "live bass", "soft Rhodes keys", "warm analog grooves"}},
	         {"Moods",
	          {"Dark", "melancholic", "laid back", "chill", "smooth", "seductive", "romantic", "energetic", "raw",
	           "contemplative", "moody", "boomy"}},
	     },
	     {
	         "Cloud Trap, nostalgic piano, plucked bass, dreamy, melancholic",
	         "Neo-Soul, soft Rhodes keys, live bass, smooth, seductive",
	         "Lofi Jazz Rap, soft Rhodes keys, plucked bass, laid back, chill",
	         "Alternative Rock, electric guitar riffs, warm analog grooves, energetic, raw",
	         "Melodic Trap, synth bells, deep sub bass, dark, moody",
	         "British 60s Oldies, vocal adlibs, airy vocal pads, romantic, contemplative",
	     }},

	    {"stablebeat",
	     "Trap drum and percussion engine. Format: [Solo/Full Beat], Instruments: drum, [Style], [Timbre], [Density]",
	     {
	         {"Format", {"Solo", "Full Beat"}},
	         {"Required", {"Instruments: drum"}},
	         {"Styles",
	          {"cloud trap beat", "melodic trap beat", "boom bap", "jazzy chillhop", "industrial hip-hop", "r&b beat"}},
	         {"Timbre",
	          {"boomy bass", "deep sub", "punchy snare", "crisp hi-hats", "dirty piano loop", "distorted kick",
	           "industrial metallic percussion"}},
	         {"Rhythmic", {"driving 4/4 beat", "syncopated rhythm", "off-beat patterns", "boomy", "rhythmic density"}},
	     },
	     {
	         "Full Beat, Instruments: drum, cloud trap beat, boomy bass, syncopated rhythm",
	         "Solo, Instruments: drum, boom bap, dirty piano loop, driving 4/4 beat",
	         "Full Beat, Instruments: drum, industrial hip-hop, distorted kick, industrial metallic percussion",
	         "Solo, Instruments: drum, jazzy chillhop, crisp hi-hats, off-beat patterns",
	         "Full Beat, Instruments: drum, melodic trap beat, deep sub, punchy snare",
	         "Solo, Instruments: drum, r&b beat, boomy, rhythmic density",
	     }},

	    {"gluten-v1",
	     "Loopable musical phrases. Format: pipe-separated. NO BPM/Key.",
	     {
	         {"Genres", {"Trap", "Melodic Trap", "Wavy Trap", "Hip-Hop", "Boom Bap", "Pop", "Ambient"}},
	         {"Instruments", {"Piano", "Synth Pad", "Synth Lead", "808 Bass", "Bells", "Strings", "Ambient Pads"}},
	         {"Moods",
	          {"Melancholic", "Reflective", "Catchy", "Smooth", "Epic", "Dark", "Atmospheric", "Building", "Ethereal",
	           "Sad", "Heavy", "Driving", "Punchy", "Rhythmic"}},
	         {"Tempo", {"Slow", "Medium", "Fast"}},
	         {"Templates", {"Format: Solo | Genre:  | Sub-Genre:  | Instruments:  | Moods:  | Styles:  | Tempo: "}},
	     },
	     {
	         "Format: Solo | Genre: Trap | Sub-Genre: Melodic Trap | Instruments: Piano, Synth Pad | Moods: "
	         "Melancholic | Styles: Catchy, Smooth | Tempo: Medium",
	         "Format: Solo | Genre: Ambient | Sub-Genre: Ambient | Instruments: Synth Pad, Strings | Moods: "
	         "Atmospheric, Ethereal | Styles: Building | Tempo: Slow",
	         "Format: Solo | Genre: Hip-Hop | Sub-Genre: Boom Bap | Instruments: Piano, 808 Bass | Moods: Sad | "
	         "Styles: Smooth | Tempo: Medium",
	         "Format: Solo | Genre: Pop | Sub-Genre: Pop | Instruments: Synth Lead, Bells | Moods: Catchy, Driving | "
	         "Styles: Punchy | Tempo: Fast",
	         "Format: Solo | Genre: Trap | Sub-Genre: Wavy Trap | Instruments: Bells, Synth Lead | Moods: Reflective, "
	         "Atmospheric | Styles: Ethereal | Tempo: Slow",
	     }},
	};
	return models;
}

const PromptModelDefinitions::ModelInfo *PromptModelDefinitions::getModel(const juce::String &modelName)
{
	for (const auto &m : getAllModels())
		if (m.modelName == modelName)
			return &m;
	return nullptr;
}